name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: grab code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: lint codebase
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: grab code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run tests
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: grab code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: deploy
        run: echo "deploying..."
